# Generated by Django 3.1.4 on 2022-12-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='priority',
        ),
    ]
