# Generated by Django 3.1.4 on 2022-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_todolistitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='content',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='from1',
            field=models.CharField(default='New palce', max_length=100),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='to',
            field=models.CharField(default='New palce', max_length=100),
        ),
    ]
