# Generated by Django 3.1.4 on 2022-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_auto_20221207_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='from1',
        ),
        migrations.RemoveField(
            model_name='todolistitem',
            name='to',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='content',
            field=models.CharField(default='New place', max_length=100),
        ),
    ]
