# Generated by Django 3.1.4 on 2022-12-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_auto_20221207_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='content',
            field=models.TextField(),
        ),
    ]
