# Generated by Django 3.1.4 on 2022-12-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_todolistitem_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='date',
        ),
    ]
