# Generated by Django 3.1.4 on 2022-12-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0007_remove_todolistitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='to',
        ),
    ]
